repos:
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    - id: flake8
# Will need to address the following when black supports the walrus operator
#-   repo: https://github.com/ambv/black
#    rev: 19.3b0
#    hooks:
#    - id: black
#      exclude: '/^staging_area_validator*\.py$/'
#      language_version: python3.8
#      args: [adapter_tools/, --skip-string-normalization]
#
