repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      exclude: '^adapter_tools/utilities/staging_area_validator.py'
      language_version: python3.8
      args: [--skip-string-normalization]
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    - id: flake8
