version: 3

groups:
  software-review:
    conditions:
      - "'eng-only' not in labels"
      - "base.ref == 'master'"
      - "base.ref == 'develop'"
    reviews:
      required: 1
      author_value: 1
      request_order: random 
    reviewers:
      users:
        - wjdingman1
        - cheyenne-gold
        - jessicaway
        - nikellepetrillo

overrides:
- if : "'Build' in check_runs.failed"
  status: failure
  explanation: "Container is failing to build"

notifications:
- when: pullapprove.approved
  if: "author_association == 'CONTRIBUTOR'"
  comment: "The review is completed. Thanks @{{ author }}."
