version: 3

groups:
  software-review:
    reviews:
      required: 1
      author_value: 1
      request_order: random 
    reviewers:
      users:
        - wjdingman1
        - cheyenne-gold
        - jessicaway
        - nikellepetrillo
      
notifications:
- when: pullapprove.approved
  if: "author_association == 'CONTRIBUTOR'"
  comment: "The review is completed. Thanks @{{ author }}."
