name: Build and Push to GCR
on: [push]
env:
  IMAGE: us.gcr.io/broad-gotc-prod/hca-adapter-tools

jobs: 
  build-push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Register github action with service account
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}

    - name: Configure docker to authenticate with gcloud
      run: |
        gcloud auth configure-docker

    - name: Build/Push all
      run: |
        export BRANCH=${GITHUB_REF#refs/heads/}
        docker build -t "${IMAGE}:${BRANCH}" .
        docker push "${IMAGE}:${BRANCH}"

    - name: Build/Push master
      if: contains ('refs/heads/master', github.ref)
      run: |
        export TIMESTAMP=$(date +"%s")
        docker build -t "${IMAGE}:latest" .
        docker tag "${IMAGE}:latest" "${IMAGE}:master_${TIMESTAMP}"
        docker push "${IMAGE}:latest"
        docker push "${IMAGE}:master_${TIMESTAMP}"

    - run: |
        echo "Successfully completed"

        
        


        
    
